name: Update Calendar

on:
  schedule:
    - cron: '0 0 * * *'   # tous les jours à minuit UTC
  workflow_dispatch:       # permet de lancer à la main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install requests ics
      - name: Generate ICS
        run: python main.py
      - name: Commit and push
        run: |
          git config user.name 'GitHub Actions'
          git config user.email 'actions@github.com'
          git add emploi.ics
          git commit -m 'Update emploi.ics' || echo 'No changes to commit'
          git push
